// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bestsellers-section/DarkFirePanel.tsx": () => import("../components/mockups/bestsellers-section/DarkFirePanel.tsx"),
  "./components/mockups/bestsellers-section/RankedSpotlight.tsx": () => import("../components/mockups/bestsellers-section/RankedSpotlight.tsx"),
  "./components/mockups/bestsellers-section/SocialProofStrip.tsx": () => import("../components/mockups/bestsellers-section/SocialProofStrip.tsx"),
  "./components/mockups/shop-categories/BoldTiles.tsx": () => import("../components/mockups/shop-categories/BoldTiles.tsx"),
  "./components/mockups/shop-categories/FeatureBanner.tsx": () => import("../components/mockups/shop-categories/FeatureBanner.tsx"),
  "./components/mockups/shop-categories/GradientCards.tsx": () => import("../components/mockups/shop-categories/GradientCards.tsx")
};
