import { db, productCategoriesTable, productsTable } from "@workspace/db";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("Clearing existing shop data...");
  await db.delete(productsTable);
  await db.delete(productCategoriesTable);

  console.log("Seeding product categories...");
  const cats = await db
    .insert(productCategoriesTable)
    .values([
      { name: "Mods & Devices", slug: "mods", description: "Box mods, mech mods, and advanced devices for cloud chasers", iconEmoji: "📦", sortOrder: 1 },
      { name: "Pod Systems", slug: "pods", description: "Compact pod kits perfect for daily use and stealth vaping", iconEmoji: "🔋", sortOrder: 2 },
      { name: "Tanks & Atomizers", slug: "tanks", description: "Sub-ohm tanks, RTAs, RDAs, and rebuildables", iconEmoji: "🛢️", sortOrder: 3 },
      { name: "E-Liquids", slug: "e-liquids", description: "Premium e-juice in every flavor profile imaginable", iconEmoji: "💧", sortOrder: 4 },
      { name: "Coils & Wire", slug: "coils", description: "Replacement coils, builder wire, and wicking supplies", iconEmoji: "🌀", sortOrder: 5 },
      { name: "Disposables", slug: "disposables", description: "Grab-and-go disposable vapes in popular flavors", iconEmoji: "⚡", sortOrder: 6 },
      { name: "Accessories", slug: "accessories", description: "Batteries, chargers, drip tips, cases, and tools", iconEmoji: "🔧", sortOrder: 7 },
    ])
    .returning();
  const cat = (slug: string) => cats.find((c) => c.slug === slug)!.id;

  console.log("Seeding products...");
  const img = (q: string) =>
    `https://images.unsplash.com/${q}?auto=format&fit=crop&w=800&q=80`;

  const products = await db
    .insert(productsTable)
    .values([
      // ─── MODS ────────────────────────────────────────────────────────────────
      {
        name: "Voltflux 220W Dual Battery Mod",
        slug: "voltflux-220w-dual",
        brand: "Voltflux",
        shortDescription: "220W dual 18650 mod with 0.001s firing and TFT color screen",
        description: "The flagship Voltflux 220W delivers blazing-fast 0.001-second firing speed across a full TC and VW range. Dual 18650 batteries (sold separately) drive a custom AS-Chip with adjustable preheat curves. A vibrant 1.45\" TFT screen makes navigating presets effortless, while the zinc-alloy chassis with leather inlay feels premium in hand.",
        priceCents: 8999,
        comparePriceCents: 11999,
        categoryId: cat("mods"),
        imageUrl: img("photo-1527661591475-527312dd65f5"),
        imageGallery: [],
        rating: "4.80",
        reviewCount: 342,
        stockCount: 47,
        inStock: true,
        isFeatured: true,
        isBestseller: true,
        isNew: false,
        tags: ["220W", "dual-battery", "TC", "VW"],
      },
      {
        name: "Stratos Mini 80W Box Mod",
        slug: "stratos-mini-80w",
        brand: "Stratos",
        shortDescription: "Compact single-battery 80W mod with intuitive joystick controls",
        description: "The Stratos Mini packs serious performance into a pocketable form factor. A single 18650 battery powers up to 80W of clean output, controlled by a clever 5-way joystick and OLED display. Perfect for vapers who want power without bulk.",
        priceCents: 4499,
        comparePriceCents: null,
        categoryId: cat("mods"),
        imageUrl: img("photo-1560923085-dc7c7e6e9e2c"),
        imageGallery: [],
        rating: "4.60",
        reviewCount: 198,
        stockCount: 82,
        inStock: true,
        isFeatured: true,
        isBestseller: false,
        isNew: true,
        tags: ["80W", "compact", "single-battery"],
      },
      {
        name: "TitanForge Hybrid Mech Mod",
        slug: "titanforge-mech",
        brand: "TitanForge",
        shortDescription: "Hand-machined brass hybrid mech mod for builders",
        description: "For experienced builders only. The TitanForge is a hand-finished hybrid mech mod cut from solid brass, featuring a silver-plated contact and floating positive pin. Build responsibly — battery safety knowledge required.",
        priceCents: 12999,
        comparePriceCents: null,
        categoryId: cat("mods"),
        imageUrl: img("photo-1605170439002-90845e8c0137"),
        imageGallery: [],
        rating: "4.90",
        reviewCount: 67,
        stockCount: 12,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: false,
        tags: ["mech-mod", "brass", "advanced"],
      },

      // ─── PODS ────────────────────────────────────────────────────────────────
      {
        name: "Aurora Pod Kit",
        slug: "aurora-pod-kit",
        brand: "NovaVape",
        shortDescription: "Slim 25W pod system with 1100mAh battery and refillable pods",
        description: "The Aurora is the perfect everyday carry. A 1100mAh battery lasts a full day of heavy use, while refillable 2ml pods accept your favorite nic salts. Auto-draw or button-fire with a satisfying tactile click.",
        priceCents: 2999,
        comparePriceCents: 3999,
        categoryId: cat("pods"),
        imageUrl: img("photo-1562813733-b31f71025d54"),
        imageGallery: [],
        rating: "4.70",
        reviewCount: 521,
        stockCount: 134,
        inStock: true,
        isFeatured: true,
        isBestseller: true,
        isNew: false,
        tags: ["pod", "MTL", "salt-nic"],
      },
      {
        name: "Caliber X Pro Pod",
        slug: "caliber-x-pro",
        brand: "Caliber",
        shortDescription: "40W variable wattage pod mod with 0.96\" color screen",
        description: "The Caliber X Pro blurs the line between pod and mod. Variable wattage up to 40W, swappable mesh coils (0.4Ω and 0.8Ω included), and a crisp color display make this a serious pod for serious vapers.",
        priceCents: 3899,
        comparePriceCents: null,
        categoryId: cat("pods"),
        imageUrl: img("photo-1571992540723-f63884a3f08c"),
        imageGallery: [],
        rating: "4.50",
        reviewCount: 287,
        stockCount: 64,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: true,
        tags: ["pod-mod", "VW", "mesh"],
      },
      {
        name: "Nimbus Stealth Pod",
        slug: "nimbus-stealth",
        brand: "Nimbus",
        shortDescription: "Ultra-thin auto-draw pod for discreet vaping",
        description: "Just 9mm thick. The Nimbus Stealth disappears in your pocket and delivers a smooth MTL draw with included 1.2Ω pods. USB-C charges in under 30 minutes.",
        priceCents: 1999,
        comparePriceCents: 2499,
        categoryId: cat("pods"),
        imageUrl: img("photo-1606127181086-d97b9eaaf6e3"),
        imageGallery: [],
        rating: "4.40",
        reviewCount: 156,
        stockCount: 218,
        inStock: true,
        isFeatured: false,
        isBestseller: true,
        isNew: false,
        tags: ["stealth", "MTL", "ultra-thin"],
      },

      // ─── TANKS ───────────────────────────────────────────────────────────────
      {
        name: "Cyclone Sub-Ohm Tank",
        slug: "cyclone-sub-ohm",
        brand: "VaporTech",
        shortDescription: "5ml mesh sub-ohm tank with adjustable bottom airflow",
        description: "The Cyclone delivers massive flavor and clouds with its triple-mesh coil system. 5ml capacity with a leak-proof top fill, and a fully adjustable bottom airflow ring lets you dial in the perfect draw.",
        priceCents: 3299,
        comparePriceCents: null,
        categoryId: cat("tanks"),
        imageUrl: img("photo-1567361294707-9d9d1f7c2bf9"),
        imageGallery: [],
        rating: "4.70",
        reviewCount: 412,
        stockCount: 89,
        inStock: true,
        isFeatured: true,
        isBestseller: true,
        isNew: false,
        tags: ["sub-ohm", "mesh", "5ml"],
      },
      {
        name: "Forge RTA 25mm",
        slug: "forge-rta-25",
        brand: "BuildCraft",
        shortDescription: "Single-coil RTA with postless deck and bottom airflow",
        description: "The Forge RTA features a postless build deck designed for single-coil flavor chasers. Bottom airflow channels target the coil directly for unmatched flavor. 4ml standard / 6ml bubble glass included.",
        priceCents: 4499,
        comparePriceCents: null,
        categoryId: cat("tanks"),
        imageUrl: img("photo-1574227492706-c86b7e69b2e2"),
        imageGallery: [],
        rating: "4.80",
        reviewCount: 178,
        stockCount: 41,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: true,
        tags: ["RTA", "single-coil", "rebuildable"],
      },
      {
        name: "Drip Squonk RDA",
        slug: "drip-squonk-rda",
        brand: "BuildCraft",
        shortDescription: "Squonk-ready dual-coil RDA with deep juice well",
        description: "Built for squonk mods. The Drip features a deep juice well, dual-coil postless deck, and 24mm honeycomb side airflow. Includes BF pin and standard pin.",
        priceCents: 3799,
        comparePriceCents: null,
        categoryId: cat("tanks"),
        imageUrl: img("photo-1610560419739-5cdac8c5b8f9"),
        imageGallery: [],
        rating: "4.60",
        reviewCount: 94,
        stockCount: 56,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: false,
        tags: ["RDA", "squonk", "dual-coil"],
      },

      // ─── E-LIQUIDS ───────────────────────────────────────────────────────────
      {
        name: "Mango Tango Ice — 60ml",
        slug: "mango-tango-ice",
        brand: "FrostLab",
        shortDescription: "Ripe mango with a chilled menthol exhale",
        description: "Bright tropical mango layered over a clean menthol breeze. FrostLab uses USP-grade ingredients and steeps every batch for two weeks before bottling.",
        priceCents: 2499,
        comparePriceCents: 2999,
        categoryId: cat("e-liquids"),
        imageUrl: img("photo-1582719471384-894fbb16e074"),
        imageGallery: [],
        rating: "4.80",
        reviewCount: 1024,
        stockCount: 312,
        inStock: true,
        isFeatured: true,
        isBestseller: true,
        isNew: false,
        flavor: "Mango / Menthol",
        nicotineStrength: "0mg / 3mg / 6mg",
        vgPgRatio: "70/30",
        bottleSize: "60ml",
        tags: ["fruit", "menthol", "tropical"],
      },
      {
        name: "Bourbon Vanilla Cream — 100ml",
        slug: "bourbon-vanilla-cream",
        brand: "Apothecary",
        shortDescription: "Smooth bourbon vanilla custard with a buttery cream finish",
        description: "An award-winning custard. Notes of aged bourbon vanilla, fresh cream, and a hint of caramelized sugar. Steeped for 30 days for maximum depth.",
        priceCents: 3499,
        comparePriceCents: null,
        categoryId: cat("e-liquids"),
        imageUrl: img("photo-1577202214328-c04b77cefb5d"),
        imageGallery: [],
        rating: "4.90",
        reviewCount: 687,
        stockCount: 178,
        inStock: true,
        isFeatured: true,
        isBestseller: true,
        isNew: false,
        flavor: "Vanilla / Custard / Bourbon",
        nicotineStrength: "0mg / 3mg / 6mg",
        vgPgRatio: "75/25",
        bottleSize: "100ml",
        tags: ["dessert", "custard", "vanilla"],
      },
      {
        name: "Strawberry Lemonade Salts — 30ml",
        slug: "strawberry-lemonade-salts",
        brand: "SaltLab",
        shortDescription: "Ripe strawberry meets tart lemonade in a smooth nic salt",
        description: "Perfect for pod systems. Sweet strawberry, freshly squeezed lemonade, and a clean nic salt finish. No throat hit harshness even at 50mg.",
        priceCents: 1999,
        comparePriceCents: null,
        categoryId: cat("e-liquids"),
        imageUrl: img("photo-1620055120238-bb9c4ffa9f5a"),
        imageGallery: [],
        rating: "4.70",
        reviewCount: 542,
        stockCount: 256,
        inStock: true,
        isFeatured: false,
        isBestseller: true,
        isNew: false,
        flavor: "Strawberry / Lemonade",
        nicotineStrength: "25mg / 50mg",
        vgPgRatio: "50/50",
        bottleSize: "30ml",
        tags: ["salt-nic", "fruit", "summer"],
      },
      {
        name: "Black Iced Coffee — 60ml",
        slug: "black-iced-coffee",
        brand: "Roast House",
        shortDescription: "Cold brew coffee with a touch of menthol",
        description: "Bold cold-brew coffee notes layered over a subtle menthol chill. No sweetness, no cream — just clean, dark coffee.",
        priceCents: 2699,
        comparePriceCents: null,
        categoryId: cat("e-liquids"),
        imageUrl: img("photo-1559496417-e7f25cb247f3"),
        imageGallery: [],
        rating: "4.50",
        reviewCount: 234,
        stockCount: 94,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: true,
        flavor: "Coffee / Menthol",
        nicotineStrength: "0mg / 3mg / 6mg",
        vgPgRatio: "70/30",
        bottleSize: "60ml",
        tags: ["coffee", "beverage", "menthol"],
      },
      {
        name: "Watermelon Bubblegum — 100ml",
        slug: "watermelon-bubblegum",
        brand: "Candyland",
        shortDescription: "Pink bubblegum stuffed with juicy watermelon",
        description: "A nostalgia-bomb. Sticky pink bubblegum with bursts of fresh watermelon. Sweet but not cloying.",
        priceCents: 2999,
        comparePriceCents: 3499,
        categoryId: cat("e-liquids"),
        imageUrl: img("photo-1599785209707-a456fc1337bb"),
        imageGallery: [],
        rating: "4.40",
        reviewCount: 389,
        stockCount: 142,
        inStock: true,
        isFeatured: true,
        isBestseller: false,
        isNew: false,
        flavor: "Watermelon / Bubblegum",
        nicotineStrength: "0mg / 3mg / 6mg",
        vgPgRatio: "70/30",
        bottleSize: "100ml",
        tags: ["candy", "fruit", "sweet"],
      },

      // ─── COILS ───────────────────────────────────────────────────────────────
      {
        name: "Cyclone Mesh Coils 5-Pack",
        slug: "cyclone-mesh-coils",
        brand: "VaporTech",
        shortDescription: "0.15Ω triple-mesh replacement coils for the Cyclone Tank",
        description: "Pack of 5 replacement 0.15Ω mesh coils for the Cyclone sub-ohm tank. Best at 60-80W. Cotton and mesh sourced from Japan.",
        priceCents: 1499,
        comparePriceCents: null,
        categoryId: cat("coils"),
        imageUrl: img("photo-1611672585731-fa10603fb9e0"),
        imageGallery: [],
        rating: "4.60",
        reviewCount: 893,
        stockCount: 412,
        inStock: true,
        isFeatured: false,
        isBestseller: true,
        isNew: false,
        tags: ["coils", "mesh", "5-pack"],
      },
      {
        name: "Aurora Pod Replacement Coils 4-Pack",
        slug: "aurora-replacement-coils",
        brand: "NovaVape",
        shortDescription: "0.8Ω mesh coils for the Aurora Pod Kit",
        description: "Pack of 4 replacement 0.8Ω mesh coils. Designed for nic-salt e-liquids at 12-18W. Plug-and-play installation.",
        priceCents: 1199,
        comparePriceCents: null,
        categoryId: cat("coils"),
        imageUrl: img("photo-1611068813580-b07c84b9d5ba"),
        imageGallery: [],
        rating: "4.50",
        reviewCount: 612,
        stockCount: 287,
        inStock: true,
        isFeatured: false,
        isBestseller: true,
        isNew: false,
        tags: ["coils", "pod", "salt-nic"],
      },
      {
        name: "Kanthal A1 Wire — 28ga 30ft",
        slug: "kanthal-a1-28ga",
        brand: "BuildCraft",
        shortDescription: "30 feet of premium Kanthal A1 resistance wire",
        description: "Top-quality Kanthal A1 for hand-built coils. 28 gauge, 30 feet on a spool. Consistent diameter and oxide layer for long-lasting builds.",
        priceCents: 999,
        comparePriceCents: null,
        categoryId: cat("coils"),
        imageUrl: img("photo-1573164574230-db1d5e960238"),
        imageGallery: [],
        rating: "4.70",
        reviewCount: 234,
        stockCount: 156,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: false,
        tags: ["wire", "kanthal", "DIY"],
      },
      {
        name: "Japanese Organic Cotton — 5g",
        slug: "japanese-organic-cotton",
        brand: "BuildCraft",
        shortDescription: "Premium unbleached cotton for clean wicks",
        description: "5g of unbleached, agricultural-grade Japanese cotton. The choice of competition vapers worldwide. No flavor interference, smooth wicking.",
        priceCents: 599,
        comparePriceCents: null,
        categoryId: cat("coils"),
        imageUrl: img("photo-1582719471384-894fbb16e074"),
        imageGallery: [],
        rating: "4.80",
        reviewCount: 478,
        stockCount: 389,
        inStock: true,
        isFeatured: false,
        isBestseller: true,
        isNew: false,
        tags: ["cotton", "wicking", "DIY"],
      },

      // ─── DISPOSABLES ────────────────────────────────────────────────────────
      {
        name: "FlashPuff 6000 — Blue Razz Ice",
        slug: "flashpuff-6000-blue-razz",
        brand: "FlashPuff",
        shortDescription: "6000-puff disposable with rechargeable battery",
        description: "Up to 6,000 puffs of icy blue raspberry. Rechargeable 600mAh battery with USB-C, 12ml of pre-filled e-liquid, and a smooth mesh coil.",
        priceCents: 1899,
        comparePriceCents: 2299,
        categoryId: cat("disposables"),
        imageUrl: img("photo-1606127181086-d97b9eaaf6e3"),
        imageGallery: [],
        rating: "4.30",
        reviewCount: 1287,
        stockCount: 423,
        inStock: true,
        isFeatured: true,
        isBestseller: true,
        isNew: false,
        flavor: "Blue Raspberry / Ice",
        nicotineStrength: "50mg",
        tags: ["disposable", "fruit", "ice"],
      },
      {
        name: "FlashPuff 6000 — Peach Mango",
        slug: "flashpuff-6000-peach-mango",
        brand: "FlashPuff",
        shortDescription: "6000-puff disposable with rechargeable battery",
        description: "Sweet ripe peach with a juicy mango finish. 6,000 puffs, rechargeable 600mAh battery, mesh coil for full flavor.",
        priceCents: 1899,
        comparePriceCents: 2299,
        categoryId: cat("disposables"),
        imageUrl: img("photo-1567361294707-9d9d1f7c2bf9"),
        imageGallery: [],
        rating: "4.40",
        reviewCount: 982,
        stockCount: 367,
        inStock: true,
        isFeatured: false,
        isBestseller: true,
        isNew: false,
        flavor: "Peach / Mango",
        nicotineStrength: "50mg",
        tags: ["disposable", "fruit"],
      },
      {
        name: "MintCloud Disposable",
        slug: "mintcloud-disposable",
        brand: "MintCloud",
        shortDescription: "2500-puff icy mint disposable",
        description: "Crisp peppermint with a cool menthol finish. 2,500 puffs, 1.4Ω mesh coil, no charging required.",
        priceCents: 1199,
        comparePriceCents: null,
        categoryId: cat("disposables"),
        imageUrl: img("photo-1571992540723-f63884a3f08c"),
        imageGallery: [],
        rating: "4.20",
        reviewCount: 654,
        stockCount: 512,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: true,
        flavor: "Peppermint / Menthol",
        nicotineStrength: "50mg",
        tags: ["disposable", "mint", "menthol"],
      },

      // ─── ACCESSORIES ────────────────────────────────────────────────────────
      {
        name: "Molicel P26A 18650 Battery — 2-Pack",
        slug: "molicel-p26a-2pack",
        brand: "Molicel",
        shortDescription: "Authentic 2600mAh 25A continuous discharge",
        description: "Industry-favorite 18650 cells. Pair of authentic Molicel P26A — 2600mAh capacity, 25A continuous discharge. Includes silicone battery case.",
        priceCents: 1899,
        comparePriceCents: null,
        categoryId: cat("accessories"),
        imageUrl: img("photo-1609091839311-d5365f9ff1c5"),
        imageGallery: [],
        rating: "4.90",
        reviewCount: 1432,
        stockCount: 234,
        inStock: true,
        isFeatured: true,
        isBestseller: true,
        isNew: false,
        tags: ["batteries", "18650", "Molicel"],
      },
      {
        name: "Xtar VC4SL 4-Bay Smart Charger",
        slug: "xtar-vc4sl-charger",
        brand: "Xtar",
        shortDescription: "4-bay USB-C smart charger with LCD display",
        description: "Charge up to 4 batteries simultaneously with independent slot control. LCD shows voltage, current, and capacity for each cell. USB-C powered.",
        priceCents: 3499,
        comparePriceCents: 3999,
        categoryId: cat("accessories"),
        imageUrl: img("photo-1583394838336-acd977736f90"),
        imageGallery: [],
        rating: "4.80",
        reviewCount: 567,
        stockCount: 98,
        inStock: true,
        isFeatured: true,
        isBestseller: false,
        isNew: false,
        tags: ["charger", "USB-C", "4-bay"],
      },
      {
        name: "Resin Drip Tip — 810",
        slug: "resin-drip-tip-810",
        brand: "DripCo",
        shortDescription: "Hand-cast resin 810 drip tip — patterns vary",
        description: "Each drip tip is hand-poured from acrylic resin, making every piece one of a kind. Standard 810 fitment. Heat-resistant and comfortable.",
        priceCents: 899,
        comparePriceCents: null,
        categoryId: cat("accessories"),
        imageUrl: img("photo-1606312619070-d48b4c652a52"),
        imageGallery: [],
        rating: "4.60",
        reviewCount: 312,
        stockCount: 187,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: true,
        tags: ["drip-tip", "810", "resin"],
      },
      {
        name: "Vape Carry Case — Compact",
        slug: "vape-carry-case",
        brand: "DripCo",
        shortDescription: "Padded EVA case for mod, tank, batteries, and juice",
        description: "Hard-shell EVA case with custom-cut foam pockets for one mod, one tank, two batteries, and a 60ml bottle. Zippered with carrying handle.",
        priceCents: 2299,
        comparePriceCents: null,
        categoryId: cat("accessories"),
        imageUrl: img("photo-1553062407-98eeb64c6a62"),
        imageGallery: [],
        rating: "4.50",
        reviewCount: 198,
        stockCount: 76,
        inStock: true,
        isFeatured: false,
        isBestseller: false,
        isNew: false,
        tags: ["case", "carry", "travel"],
      },
    ])
    .returning();

  console.log(`Seeded ${cats.length} categories and ${products.length} products`);

  // Update product counts per category
  for (const c of cats) {
    const count = products.filter((p) => p.categoryId === c.id).length;
    await db
      .update(productCategoriesTable)
      .set({ productCount: count })
      .where(sql`${productCategoriesTable.id} = ${c.id}`);
  }

  console.log("✓ Shop data seeded successfully");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
